### ISSUE TITLE
1.7.10 - compiled?

### ISSUE THREAD

**Issue by silent-mobious** [runescapejon/More-Health-Enhanced#1]
Hi there.  Don't suppose you've got an old version with your fixes that's compiled?  My Java-fu is horrible and I've thrown what little I can think of at it but near as I can tell it looks like it's failing to compile since I'm not using a 1.6 JDK?  Any ideas of other things I can try?

warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/silent/minecraft/build/More-Health-Enhanced/build/sources/java/com/nohero/morehealth/EventHandlers/FMLEventHandler.java:22: error: package TickEvent does not exist
  public void onPlayerLivingUpdate(TickEvent.PlayerTickEvent event)

Thanks!

**Comment by runescapejon** [comment]
I haven't tested but here a compile https://github.com/runescapejon/More-Health-Enhanced/releases/tag/6.5

and also did a general clean up on the code

**Comment by silent-mobious** [comment]
Hot Dang!!  I got lots of hearts, and I died on my server finally!  :)  Awesome!  Thanks so much for the quick fixup!!!
